In [7]:
from coco_names import COCO_INSTANCE_CATEGORY_NAMES as coco_names
import numpy as np

In [5]:
print(coco_names)

['__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'N/A', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'N/A', 'backpack', 'umbrella', 'N/A', 'N/A', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'N/A', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'N/A', 'dining table', 'N/A', 'N/A', 'toilet', 'N/A', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'N/A', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']


In [10]:
COLORS = np.random.uniform(0, 255, size=(len(coco_names), 3)).astype(np.uint8)

In [11]:
print(COLORS)

[[211 110  83]
 [193  33 194]
 [225 184 169]
 [ 36 131  32]
 [166  34 108]
 [246 195  59]
 [149  89  25]
 [ 30  56 191]
 [ 79  19 183]
 [ 67 202 248]
 [155  93 117]
 [154 179  74]
 [217  38 121]
 [ 61 162 164]
 [202 254   6]
 [ 16 138  88]
 [ 25 248  33]
 [208 140  61]
 [253 168 254]
 [ 82 162 181]
 [140 226  57]
 [  4  34  90]
 [187  50  21]
 [ 24 200 131]
 [222 246  72]
 [135  58 106]
 [ 80  56 195]
 [180 242 163]
 [141  74  38]
 [ 71 210 155]
 [ 75  46  76]
 [120 243  94]
 [177  66 230]
 [ 19  70  67]
 [ 83  64  87]
 [  9  76 214]
 [ 73  94 186]
 [153  10 112]
 [ 88  58  19]
 [ 25   3  57]
 [ 93 127 164]
 [ 75 139 117]
 [241  60  73]
 [183   0 177]
 [101 127 131]
 [159 199  19]
 [ 76 226  96]
 [ 54   4  45]
 [145 111 232]
 [ 39 217 201]
 [237  18  49]
 [ 34 114 217]
 [127 159 182]
 [189   7  26]
 [ 10 201  88]
 [ 67 128 216]
 [199 167  60]
 [220 109 221]
 [ 58  72  38]
 [ 90 195 132]
 [ 76 228  92]
 [139  99 108]
 [188  12  19]
 [242 166   6]
 [  3  52 170]
 [198 242  75]
 [ 87 138 

In [12]:
COLORS.tolist()

[[211, 110, 83],
 [193, 33, 194],
 [225, 184, 169],
 [36, 131, 32],
 [166, 34, 108],
 [246, 195, 59],
 [149, 89, 25],
 [30, 56, 191],
 [79, 19, 183],
 [67, 202, 248],
 [155, 93, 117],
 [154, 179, 74],
 [217, 38, 121],
 [61, 162, 164],
 [202, 254, 6],
 [16, 138, 88],
 [25, 248, 33],
 [208, 140, 61],
 [253, 168, 254],
 [82, 162, 181],
 [140, 226, 57],
 [4, 34, 90],
 [187, 50, 21],
 [24, 200, 131],
 [222, 246, 72],
 [135, 58, 106],
 [80, 56, 195],
 [180, 242, 163],
 [141, 74, 38],
 [71, 210, 155],
 [75, 46, 76],
 [120, 243, 94],
 [177, 66, 230],
 [19, 70, 67],
 [83, 64, 87],
 [9, 76, 214],
 [73, 94, 186],
 [153, 10, 112],
 [88, 58, 19],
 [25, 3, 57],
 [93, 127, 164],
 [75, 139, 117],
 [241, 60, 73],
 [183, 0, 177],
 [101, 127, 131],
 [159, 199, 19],
 [76, 226, 96],
 [54, 4, 45],
 [145, 111, 232],
 [39, 217, 201],
 [237, 18, 49],
 [34, 114, 217],
 [127, 159, 182],
 [189, 7, 26],
 [10, 201, 88],
 [67, 128, 216],
 [199, 167, 60],
 [220, 109, 221],
 [58, 72, 38],
 [90, 195, 132],
 [76, 228, 9

In [ ]:
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]